const routes = [
  { path: "/", exact: true },
  { path: "/user/profile" },
  { path: "/user/order" },

  { path: "/" },
  { path: "/nutrition/gomzi-nutrition-whey-protein-concentrate" },
  { path: "/nutrition/gomzi-nutrition-whey-protein-isolate" },
  { path: "/nutrition/gomzi-nutrition-whey-protein-chocolate" },
  { path: "/nutrition/gomzi-nutrition-ignite-fat-burner" },
  { path: "/nutrition/gomzi-nutrition-spark-eaa" },
  { path: "/nutrition/gomzi-nutrition-atp-creatine" },
  { path: "/nutrition/gomzi-nutrition-mass-gainer-powder" },
  { path: "/nutrition/gomzi-nutrition-muscle-build-combo" },
  { path: "/nutrition/gomzi-nutrition-fat-loss-combo" },
  { path: "/nutrition/gomzi-nutrition-buy-1kg-isolate" },
  { path: "/nutrition/gomzi-nutrition-all-combo" },
  { path: "/nutrition/gomzi-nutrition-shaker-bottle" },
  { path: "/nutrition/gomzi-nutrition-bowlease-constipation-relief-powder" },
  { path: "/nutrition/gomzi-nutrition-sugarguard-diabetes-care-powder" },
  { path: "/nutrition/gomzi-nutrition-ayurease-gastric-relief-powder" },
  { path: "/nutrition/gomzi-nutrition-b12-veda" },
  { path: "/nutrition/gomzi-nutrition-slimayur-fat-loss-powder" },
  { path: "/nutrition/gomzi-nutrition-ayurstrength-powder" },
  { path: "/nutrition/white-labelling" },
  { path: "/nutrition/bulk-inquiry-nutrition" },
  { path: "/nutrition/trainer-nutrition" },
  { path: "/nutrition/check-out" },
  { path: "/nutrition/terms-condition-customer" },
  { path: "/nutrition/thank-you-for-order" },
  { path: "/user/profile" },
  { path: "/user/order" },
];

module.exports = routes;
